# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  calculadora:
    image: calculadora
    build:
      context: .
      dockerfile: Calculadora/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5023:5023
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
